# Generated by Django 6.0.7 on 2026-09-25 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking_app', '0002_shift'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminderlog',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reminderlog',
            name='reminder_type',
            field=models.CharField(default='MANUAL', max_length=20),
        ),
        migrations.AddField(
            model_name='reminderlog',
            name='whatsapp_message_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
